project_name: nametidy

builds:
  - id: macos
    main: ./cmd/ghqx/main.go
    goos: [darwin]
    goarch: [amd64]

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_darwin_amd64'

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_macos_checksums.txt"

release:
  draft: false
  prerelease: false
